### ISSUE TITLE
Is there a plan to release bootkube with 1.13 or higher k8s?

### ISSUE THREAD

**Issue by HarithaRamesh** [kubernetes-sigs/bootkube#1042]
Asking this because, it's been a year almost since a new release, and I'd like to know when the next release will be made.

**Comment by smekkley** [comment]
’bootkube render’ produces example configs. It's already compatible with the latest k8s, calico, or any other network plugins. It also works with podsecurity. Maybe we should put just example yaml in repo, and make bootkube only produce certificate related files to focus on bigger issue like making it compatible with apiserver liveliness check and making recover option completely ready

**Comment by HarithaRamesh** [comment]
Hmm. What I'm concerned about is if the example configs from bootkube render that use the 1.12 hyperkube are compatible with higher k8s hyperkube image -- latest k8s is currently at 1.15.

**Comment by andrewrynhard** [comment]
There is also some breaking changes in the client. I have local changes that upgrades to 1.16.  Seems to work just fine.

**Comment by rmenn** [comment]
The render part of this repo is still under discussion, it was mainly put in place for CI to generate manifests which are usable, if you update the manifests to use 1.16 and the node labels you should have a working cluster

**Comment by smekkley** [comment]
Just bumping the version of the render output doesn't work anymore. Typhoon has fairly good example as well. 
I think it's too much burden to keep render up to date including following best practice, especially if render is also used in CI. I vote for having example directories where they can more casually merged to master.

**Comment by rmenn** [comment]
This is being worked on, as you mentioned there are a few changes which are required

**Comment by rmenn** [comment]
I have a working version of bootkube at this time, i am waiting on changes to the repo ( being moved to kubernetes-sigs ) to wrap up prior to PR. 

If you want to check it out https://github.com/rmenn/bootkube/tree/kube_update_1.16

An image is also available here : quay.io/rmenn/bootkube:v0.15.0

**Comment by rmenn** [comment]
#1056 once merged will support 1.16.2

**Comment by rmenn** [comment]
this is now available, but we however do not have a release for it
