### ISSUE TITLE
Proposal : CNI Support

### ISSUE THREAD

**Issue by rmenn** [kubernetes-sigs/bootkube#1072]
Putting forward a proposal where we

* Continue to maintain flannel
* Drop Support for canal
* Try and graduate calico from experimental

Please react with :+1: if you agree with the plan, :question: if you think dropping canal is a problem.

**Comment by andrewrynhard** [comment]
I'm for this. Maintaining CNI manifests is not gonna scale. An easy way for users to bring there own CNI manifests will go far.

**Comment by aaronlevy** [comment]
Are network policies part of the conformance test suite? That would be my one concern about prioritizing flannel over canal.

**Comment by rmenn** [comment]
not at this time, i have not seem network policy based conformance tests
