### ISSUE TITLE
Can no longer execute "make vendor"

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/bootkube#1091]
On latest master (d8e5fa33347a90c3efaad3f2ab0c49478aba7e68):
```
$ make vendor
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   848  100   848    0     0   6328      0 --:--:-- --:--:-- --:--:--  6328
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4334  100  4334    0     0  30097      0 --:--:-- --:--:-- --:--:-- 29889
can't load package: package ./vendor/github.com/coreos/license-bill-of-materials: cannot find package "." in:
        /home/invidian/repos/kinvolk/bootkube/vendor/github.com/coreos/license-bill-of-materials
make: *** [Makefile:82: vendor] Error 1
```

**Comment by andrewrynhard** [comment]
We actually don't need the vendor dir anymore. We should remove it entirely.

**Comment by vbatts** [comment]
What to do with generating the license-bill-of-material?

**Comment by andrewrynhard** [comment]
@vbatts I don't have a good answer yet. Maybe we could have some temporary place we can do `go mod vendor`, generate what we need from that, and then dispose of it. However, IIRC vendoring will eventually go away with golang, but maybe that is far off enough that we shouldn't worry about it just yet.

**Comment by rmenn** [comment]
IIRC livence-bill-of-material is something inherited from coreos, im unsure if we need to keep it

**Comment by mrbobbytables** [comment]
This project is being archives, for more information see this issue:
https://github.com/kubernetes/org/issues/2824

/close
