### ISSUE TITLE
Check if tests runs properly in CI

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/bootkube#1094]
While working on #1092, I found that many `e2e` tests had broken syntax, so it might be, that they are not run frequently enough. I think that should be investigated.

**Comment by rmenn** [comment]
Yeah the entire CI does not run since it was running on a jenkins which was internal to coreos, we need to move hopefully to prow

**Comment by invidian** [comment]
@rmenn I'm not familiar with setting up prow. Could you send some pointers where to look on how to use it?

**Comment by mrbobbytables** [comment]
This project is being archives, for more information see this issue:
https://github.com/kubernetes/org/issues/2824

/close
