### ISSUE TITLE
Bootkube - Bare-metal documentation link is broken

### ISSUE THREAD

**Issue by ashokspeelyaal** [kubernetes-sigs/bootkube#1095]
When I click "Bare-Metal" link under "Guides", It is not directing to the guide. I end up seeing 404 page. 

https://github.com/poseidon/matchbox/tree/master/examples/terraform/bootkube-install

**Comment by dghubble** [comment]
The docs to which this project is linking were removed last year. https://github.com/poseidon/matchbox/pull/759
