### ISSUE TITLE
Pod cannot obtain pod ip

### ISSUE THREAD

**Issue by shelley1902** [kubernetes-sigs/bootkube#1098]
The cni plugin used is flannel, and the pod will restart from time to time。The kubelet log reports the following error:
**failed to read pod IP from plugin/docker: networkPlugin cni failed on the status hook for pod "pod-case-01": unexpected address output**

**Comment by andrewrynhard** [comment]
@shelley1902 This sounds like a flannel issue. We should probably look at upgrading the default version of flannel.
