### ISSUE TITLE
Figure out how we can re-enable healthchecks on the kube-apiserver

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-sigs/bootkube#495]
We disable healthchecks on the api-server because paired with bootstrapping and checkpointing, they can make the pivot process somewhat flaky due to the apiserver using an flock (and "running", but not actually serving requests).

For example during bootstrap:

- bootstrap api-server starts (acquires lock)
- self-hosted api-server starts (waits on lock)
- kubelet tries to health-check self-hosted api-server, but fails (not listening yet)
- kubelet keeps restarting apiserver over and over
- eventually bootstrap api-server stops (and gives up lock)
- As long as the kubelet doesn't die in this window, it will eventually restart the self-hosted apiserver (but this could be a long window due to backoff).

Or during checkpointing:

- api-server is down
- Start a checkpointed copy of apiserver (and acquire lock)
- eventually self-hosted api-server comes back up (waits on lock)
- kubelet tries health-check on self-hosted apiserver and fails (because it's not listening yet)
- kubelet keeps restarting apiserver container over and over
- The problem here is that the checkpointer must use the /runningcontainers endpoint to determine if there is a local apiserver running (https://github.com/kubernetes-incubator/bootkube/blob/0a9b736d7e99a9156a2e6d7ce084213f9a19032a/cmd/checkpoint/main.go#L34-L36), because the kubelet's /pod endpoint could have stale data. However, the /runningcontainers endpoint is only looking at the container runtime state - which means that it might think that no apiserver is running (if it looks while kubelet is restarting the apiserver - there is no container). It then thinks it needs to restart the checkpointed copy of the api-server, then starts process over again. This leads to it sometimes eventually settling down based on timing, but it is quite flaky. 

We could revisit how we determine local running state. Or maybe revist the lock process (upstream something like the kubelet lock, where you can specify "exit-on-lock-contention" so we can coordinate control between two components). Or we might continue to work around it maybe by doing something like using an `exec` healthcheck that is aware of the lock state (via @chancez).

**Comment by jamiehannaford** [comment]
Some of kubelet's flock stuff is in [`util/flock`](https://github.com/kubernetes/kubernetes/tree/master/pkg/util/flock), so it can be re-used. The `--exit-on-lock-contention` code which monitors the lock file is [here](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server_linux.go#L24) but can probably be shifted over. I'm wondering if a readiness probe can be set up using something like inotify to pass the moment the self-hosted apiserver acquires the lock. Then a HTTP liveness probe will ensure the pod can serve traffic, with an `initialDelaySeconds` that equals or slightly exceeds the flock `--timeout`. What do you think?

**Comment by aaronlevy** [comment]
The readiness probe against the lock is an interesting idea. IIRC, however, the liveness would be checked prior to readiness (and would still cause the pod to die). Could be wrong on that though.

Also @diegs and I were talking about this yesterday, and we may not need the lock at all. This is mostly to protect against flapping during checkpointing. From another thread:

> We have to use two api endpoints on the kubelet (/pods and /runningpods) to safely make checkpointing decisions. The /pods endpoint gives us the internal representation of what the kubelet thinks is the local state. These are full pod-specs/status. However, this data is only updated *after* it is successfully been persisted to the apiserver. So the process is "inspect local state to populate a list of pods --> update apiserver --> update internal state --> can now be queried by /pods". If an apiserver cannot be contacted -- this data becomes stale (represents state the last time it could successfully contact an apiserver).

> The "/runningpods" endpoint, however, is the local state as populated by the container runtime. This information is up to date regardless of whether an apiserver can be contacted. It also is only a small subset of the podspec/status.

> Because the /pods endpoint could be stale when an apiserver is absent -- we can't make "should we start/stop this checkpointed pod" decisions based solely on that information. For example, we could check /pods and see that an apiserver pod is in a running state, when it really is not. 

> Instead we need to rely on the "/runningpods" endpoint which is essentially a direct mapping to `docker ps`. The problem here with port conflicts is that when the checkpointer checks /runningpods -- the apiserver pods might be fighting over the port and in a failure loop. So it will go into "should start checkoint" then "should stop checkpoint" over and over again because it may see the pod happened to try to run, or no pod running purely depending on that moment in time. 

> The flock allows us to see, for example, that when /runningpods is called the "replacement" apiserver pod is in fact running (even if its just sitting on the flock) -- so the checkpointer can stop the checkpointed copy -- then lets the real apiserver take over.

However, all we really care about is checking the "intention" of running a pod, which we could also enforce by having a container that does nothing but sleep forever. This way when we query /runningpods we will see the apiserver pod (even if it's in a failure loop), because one container of the pod (sleep forever) is still running.

(some testing on this is being done in: https://github.com/kubernetes-incubator/bootkube/pull/525/files#diff-1a342de84d1bbb83d110cdca78afa143R153)

**Comment by jamiehannaford** [comment]
> IIRC, however, the liveness would be checked prior to readiness (and would still cause the pod to die)

Not if you set the `initialDelaySeconds` higher or equal to the flock timeout. After 30s, the apiserver will either be running (and the liveness probe will begin) or dead because it hasn't acquired the lock (in which case no liveness probe ever runs). That's my assumption though.

> However, all we really care about is checking the "intention" of running a pod, which we could also enforce by having a container that does nothing but sleep forever. This way when we query /runningpods we will see the apiserver pod (even if it's in a failure loop), because one container of the pod (sleep forever) is still running.

I get how this might help from a checkpointing perspective, but what about the scenario outlined in https://github.com/kubernetes/kubernetes/issues/45786 where there are race conditions. You'd still need some way of:

1. Ensuring that the self-hosted pod starts up after the bootstrap one in a synchronised way
2. Ensuring that the self-hosted pod is actually listening when it should be (including anticipated delays when we know it might not be)

Would the sleeping sidecar address these as well or are you just thinking about it from a checkpointing POV?

**Comment by aaronlevy** [comment]
> all we really care about is checking the "intention" of running a pod, which we could also enforce by having a container that does nothing but sleep forever. This way when we query /runningpods we will see the apiserver pod (even if it's in a failure loop), because one container of the pod (sleep forever) is still running.

As a side-note, last I looked into this we don't actually need a sidecar or a flock for the checkpointing -- the `/runningpods` endpoint will still list the pod because the pause pod is still there (even if the actual apiserver container has died). This is how we can determine "intention".

It's been a while since I looked to make sure our code respects that -- but it should just be looking for the pod by name (and it would be in the `/runningpods` output with just the 'pause' container

**Comment by aaronlevy** [comment]
Looks like etcd health has been added to the apiserver healthcheck: https://github.com/kubernetes/kubernetes/pull/49412 -- that makes re-enabling this even more useful.

There have been reports that when replacing an etcd node the apiserver doesn't actually try and re-establish a connection. I haven't validated this - but this type of check would mitigate that (would restart the apiserver if healthcheck failed).

**Comment by rmenn** [comment]
This is something we need to get into render so that its enabled by default. Hopefully we should target 1.17

**Comment by invidian** [comment]
I use `readinessProbe` for `kube-apiserver` Pod in [Flexkube](https://github.com/flexkube/kube-apiserver-helm-chart/blob/master/templates/deployment.yaml#L182-L186), however, I don't use `pod-checkpointer` at the moment. However, I use `SO_REUSEPORT` for `kube-apiserver` Pod, which will be added in 1.19, so I can have multiple instances running at a time (the readiness probe check however, is satisfied if any instance is running, as it runs on host network, which is not great).

I plan to use `pod-checkpointer` to avoid keeping static controlplane running. However, it seems to me, that for automatic recovery, `kube-controller-manager` and `kube-scheduler` pods should also be checkpointed, but they should have a different checkpointing mechanism than `kube-apiserver`. For those pods, leader election should be checked instead.

I've also experienced some flakyness with `pod-checkpointer` while working on Lokomotive, so perhaps `pod-checkpointer` needs some improvements to resolve this.

**Comment by andrewrynhard** [comment]
@invidian We see this often with `pod-checkpointer`. I think we should absolutely look into this, soon. Would you be up for a meeting on this?

**Comment by invidian** [comment]
@andrewrynhard meeting sounds good, though I don't have much knowledge about the `pod-checkpointer`. Let's coordinate on Slack :+1:

**Comment by mrbobbytables** [comment]
This project is being archived, for more information see this issue:
https://github.com/kubernetes/org/issues/2824

/close
