### ISSUE TITLE
Enable podSecurityPolicy by default

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-sigs/bootkube#782]
Broken out of discussion in: https://github.com/kubernetes-incubator/bootkube/issues/660

We should enable - then have a pretty locked-down default, and documentation for allowing more "permissive" policies.

/cc @ericchiang @joshrosso

**Comment by ericchiang** [comment]
@colemickens volunteered to work on this btw.

**Comment by bcg62** [comment]
a little shocked to use booktube and find it wide open by default. +1 for this.

**Comment by redbaron** [comment]
@bcg62 , PSP is not an easy ride, every ServiceAccount need to be granted permission to use some PSP and not other. PSPs need to be prepared for many core services. Once enabled almost all ready-made yaml/helm charts are going to fail (should you have strict enough default PSP of course, which is the whole point of this exercise).

**Comment by ericchiang** [comment]
> a little shocked to use booktube and find it wide open by default. +1 for this.

Agreed, I think this is a bit hyperbolic. PSPs are just being brought to a usable state in 1.9.

**Comment by surajssd** [comment]
I would like to take this up.

**Comment by andrewrynhard** [comment]
Enabled by default and locked down completely is something I'd like to see. I much rather prefer a "secure by default" approach. Makes any insecure settings a conscience choice made by the user.

**Comment by rata** [comment]
@andrewrynhard we are doing it in https://github.com/kinvolk/terraform-render-bootkube (it uses bootkube files as base, they are slightly modified for PSPs and templating via terraform).

I think it makes total sense to add it in bootkube. However, not sure if the idea is to remove PSP and use OPA in the future, though.

**Comment by andrewrynhard** [comment]
Yeah I’m not too excited about being forced to use OPA 😔.

**Comment by rata** [comment]
Do we want this to auto close or do we want to keep it open and comment on progress here? Didn't attend to the latest meeting, not sure if the idea is to move forward with this

**Comment by andrewrynhard** [comment]
This is really a question of rendering. And we are fleshing out a proposal for a plugin style setup for rendering. This may not apply to bootkube soon. At this point I'm tempted to let this stay rotten.

**Comment by invidian** [comment]
We have a plugin based rendering now, so maybe we can close this?

**Comment by andrewrynhard** [comment]
Works for me.

**Comment by invidian** [comment]
I think we could re-visit that once we upgrade to latest Kubernetes version etc. Perhaps in the meanwhile situation with PSPs gets improved somehow upstream.

**Comment by invidian** [comment]
PSPs will be deprecated in K8s 1.21 BTW.

**Comment by mrbobbytables** [comment]
This project is being archived, for more information see this issue:
https://github.com/kubernetes/org/issues/2824

/close
