### ISSUE TITLE
allow --cloud-config to be specified

### ISSUE THREAD

**Issue by bkcsfi** [kubernetes-sigs/bootkube#916]
somewhat related to #754

To support volumes on vsphere I need to specify both --cloud-provider=vsphere AND --cloud-config=<some path>

It looks like bootkube does not support passing in --cloud-config anywhere.

I'm not looking for bootkube to do anything other than allow these parameters to be passed into the appropriate manifests.

I could try to create a PR if someone gave me a hint where to start..

thanks

**Comment by rmenn** [comment]
Could you give a sample cloud-config or point me to docs?

**Comment by invidian** [comment]
I wonder if this could be supported using custom rendered plugin or maybe with kustomize somehow?

**Comment by mrbobbytables** [comment]
This project is being archived, for more information see this issue:
https://github.com/kubernetes/org/issues/2824

/close
